/**
 * llmVendorData.ts — Static LLM vendor + model registry
 *
 * Contains VENDOR_CATALOGUE_RAW: the full list of LLM providers and their models.
 * Scoring and recommendation logic lives in llmScoring.ts.
 * Public API (helpers + final catalogue) lives in llmCatalogue.ts (barrel).
 */
import type { LLMVendor } from "./llmTypes";

export const VENDOR_CATALOGUE_RAW: LLMVendor[] = [
  // ── Google ────────────────────────────────────────────────────────────────
  {
    id: "google",
    displayName: "Google DeepMind",
    shortName: "Google",
    logoColor: "#4285F4",
    models: [
      {
        id: "gemini-2.5-pro",
        displayName: "Gemini 2.5 Pro",
        description: "Best reasoning and writing quality in the 2.5 family.",
        contextWindow: 1048576,
        outputTokens: 65536,
        tier: "flagship",
        speed: "powerful",
      },
      {
        id: "gemini-2.5-flash",
        displayName: "Gemini 2.5 Flash",
        description: "Fast, accurate, 1M context. Recommended default for bulk enrichment.",
        contextWindow: 1048576,
        outputTokens: 65536,
        tier: "balanced",
        speed: "balanced",
      },
      {
        id: "gemini-2.5-flash-lite",
        displayName: "Gemini 2.5 Flash-Lite",
        description: "Lightest 2.5 model. Best for high-volume tasks with tight latency.",
        contextWindow: 1048576,
        outputTokens: 65536,
        tier: "lite",
        speed: "fast",
      },
      {
        id: "gemini-3.1-pro-preview",
        displayName: "Gemini 3.1 Pro Preview",
        description: "Latest preview — most capable for complex reasoning and long-form writing.",
        contextWindow: 1048576,
        outputTokens: 65536,
        tier: "flagship",
        speed: "powerful",
      },
      {
        id: "gemini-3-flash-preview",
        displayName: "Gemini 3 Flash Preview",
        description: "Gemini 3 Flash preview — fast and capable.",
        contextWindow: 1048576,
        outputTokens: 65536,
        tier: "fast",
        speed: "fast",
      },
      {
        id: "nano-banana",
        displayName: "Nano Banana (Image Gen)",
        description: "Google Nano Banana — state-of-the-art image generation model for AI avatars.",
        contextWindow: 0,
        outputTokens: 0,
        tier: "image-gen",
        speed: "balanced",
        imageGen: true,
      },
    ],
  },

  // ── OpenAI ────────────────────────────────────────────────────────────────
  {
    id: "openai",
    displayName: "OpenAI",
    shortName: "OpenAI",
    logoColor: "#10A37F",
    models: [
      {
        id: "gpt-4o",
        displayName: "GPT-4o",
        description: "Flagship multimodal model. Best overall quality for complex tasks.",
        contextWindow: 128000,
        outputTokens: 16384,
        tier: "flagship",
        speed: "powerful",
      },
      {
        id: "gpt-4o-mini",
        displayName: "GPT-4o Mini",
        description: "Smaller, faster, cheaper GPT-4o. Great for high-volume enrichment.",
        contextWindow: 128000,
        outputTokens: 16384,
        tier: "balanced",
        speed: "fast",
      },
      {
        id: "o3",
        displayName: "o3",
        description: "Advanced reasoning model. Best for multi-step analysis and research.",
        contextWindow: 200000,
        outputTokens: 100000,
        tier: "flagship",
        speed: "powerful",
      },
      {
        id: "o4-mini",
        displayName: "o4-mini",
        description: "Fast reasoning model. Good balance of speed and analytical depth.",
        contextWindow: 200000,
        outputTokens: 100000,
        tier: "balanced",
        speed: "balanced",
      },
      {
        id: "gpt-4.1",
        displayName: "GPT-4.1",
        description: "Latest GPT-4 generation. Improved instruction following and coding.",
        contextWindow: 1000000,
        outputTokens: 32768,
        tier: "flagship",
        speed: "powerful",
      },
    ],
  },

  // ── Anthropic ─────────────────────────────────────────────────────────────
  {
    id: "anthropic",
    displayName: "Anthropic",
    shortName: "Anthropic",
    logoColor: "#D97706",
    models: [
      {
        id: "claude-opus-4-5-20251101",
        displayName: "Claude Opus 4.5",
        description: "Most capable Claude model. Best for nuanced writing and deep research.",
        contextWindow: 200000,
        outputTokens: 32000,
        tier: "flagship",
        speed: "powerful",
      },
      {
        id: "claude-sonnet-4-5-20250929",
        displayName: "Claude Sonnet 4.5",
        description: "Best balance of speed and quality in the Claude 4 family.",
        contextWindow: 200000,
        outputTokens: 16000,
        tier: "balanced",
        speed: "balanced",
      },
      {
        id: "claude-haiku-4-5-20251001",
        displayName: "Claude Haiku 4.5",
        description: "Fastest Claude model. Ideal for bulk processing and simple tasks.",
        contextWindow: 200000,
        outputTokens: 8192,
        tier: "lite",
        speed: "fast",
      },
      {
        id: "claude-opus-4-20250514",
        displayName: "Claude Opus 4",
        description: "High-performance flagship model with excellent reasoning capabilities.",
        contextWindow: 200000,
        outputTokens: 32000,
        tier: "flagship",
        speed: "powerful",
      },
      {
        id: "claude-sonnet-4-20250514",
        displayName: "Claude Sonnet 4",
        description: "Balanced model with strong reasoning and coding capabilities.",
        contextWindow: 200000,
        outputTokens: 16000,
        tier: "balanced",
        speed: "balanced",
      },
      {
        id: "claude-3-5-haiku-20241022",
        displayName: "Claude 3.5 Haiku",
        description: "Lightweight fast model. Good for simple tasks and bulk processing.",
        contextWindow: 200000,
        outputTokens: 8192,
        tier: "lite",
        speed: "fast",
      },
    ],
  },

  // ── xAI (Grok) ───────────────────────────────────────────────────────────
  {
    id: "xai",
    displayName: "xAI",
    shortName: "Grok",
    logoColor: "#000000",
    models: [
      {
        id: "grok-3",
        displayName: "Grok 3",
        description: "xAI's flagship model. Strong reasoning with real-time knowledge.",
        contextWindow: 131072,
        outputTokens: 16384,
        tier: "flagship",
        speed: "powerful",
      },
      {
        id: "grok-3-mini",
        displayName: "Grok 3 Mini",
        description: "Efficient Grok 3 variant. Fast inference for structured tasks.",
        contextWindow: 131072,
        outputTokens: 16384,
        tier: "balanced",
        speed: "fast",
      },
      {
        id: "grok-3-mini-fast",
        displayName: "Grok 3 Mini Fast",
        description: "Fastest Grok variant. Optimized for low-latency bulk operations.",
        contextWindow: 131072,
        outputTokens: 16384,
        tier: "lite",
        speed: "fast",
      },
    ],
  },

  // ── DeepSeek ──────────────────────────────────────────────────────────────
  {
    id: "deepseek",
    displayName: "DeepSeek",
    shortName: "DeepSeek",
    logoColor: "#4D6BFE",
    models: [
      {
        id: "deepseek-v3",
        displayName: "DeepSeek V3",
        description: "Flagship MoE model. Exceptional coding and reasoning at low cost.",
        contextWindow: 128000,
        outputTokens: 8192,
        tier: "flagship",
        speed: "powerful",
      },
      {
        id: "deepseek-r1",
        displayName: "DeepSeek R1",
        description: "Reasoning-focused model with chain-of-thought capabilities.",
        contextWindow: 128000,
        outputTokens: 8192,
        tier: "flagship",
        speed: "powerful",
      },
      {
        id: "deepseek-v3-0324",
        displayName: "DeepSeek V3 (March 2024)",
        description: "Updated V3 with improved instruction following and coding.",
        contextWindow: 128000,
        outputTokens: 8192,
        tier: "balanced",
        speed: "balanced",
      },
    ],
  },

  // ── Meta ──────────────────────────────────────────────────────────────────
  {
    id: "meta",
    displayName: "Meta AI",
    shortName: "Meta",
    logoColor: "#0866FF",
    models: [
      {
        id: "llama-4-maverick",
        displayName: "Llama 4 Maverick",
        description: "Meta's flagship multimodal model with 128 experts MoE architecture.",
        contextWindow: 1000000,
        outputTokens: 16384,
        tier: "flagship",
        speed: "powerful",
      },
      {
        id: "llama-4-scout",
        displayName: "Llama 4 Scout",
        description: "Efficient Llama 4 variant. 10M context window, fast inference.",
        contextWindow: 10000000,
        outputTokens: 16384,
        tier: "balanced",
        speed: "fast",
      },
      {
        id: "llama-3-3-70b",
        displayName: "Llama 3.3 70B",
        description: "Proven open-weight model. Strong reasoning and instruction following.",
        contextWindow: 128000,
        outputTokens: 8192,
        tier: "balanced",
        speed: "balanced",
      },
    ],
  },

  // ── Mistral ───────────────────────────────────────────────────────────────
  {
    id: "mistral",
    displayName: "Mistral AI",
    shortName: "Mistral",
    logoColor: "#FF7000",
    models: [
      {
        id: "mistral-large-2",
        displayName: "Mistral Large 2",
        description: "Flagship Mistral model. Strong multilingual and coding capabilities.",
        contextWindow: 128000,
        outputTokens: 8192,
        tier: "flagship",
        speed: "powerful",
      },
      {
        id: "mistral-small-3",
        displayName: "Mistral Small 3",
        description: "Efficient and fast. Best cost-performance for structured tasks.",
        contextWindow: 32000,
        outputTokens: 8192,
        tier: "balanced",
        speed: "fast",
      },
      {
        id: "codestral-2501",
        displayName: "Codestral 2501",
        description: "Specialized for code generation and analysis.",
        contextWindow: 256000,
        outputTokens: 8192,
        tier: "flagship",
        speed: "balanced",
      },
    ],
  },

  // ── Cohere ────────────────────────────────────────────────────────────────
  {
    id: "cohere",
    displayName: "Cohere",
    shortName: "Cohere",
    logoColor: "#39594D",
    models: [
      {
        id: "command-r-plus",
        displayName: "Command R+",
        description: "Flagship RAG-optimized model. Best for retrieval-augmented generation.",
        contextWindow: 128000,
        outputTokens: 4096,
        tier: "flagship",
        speed: "powerful",
      },
      {
        id: "command-r",
        displayName: "Command R",
        description: "Efficient RAG model. Good balance of speed and retrieval quality.",
        contextWindow: 128000,
        outputTokens: 4096,
        tier: "balanced",
        speed: "balanced",
      },
      {
        id: "command-a",
        displayName: "Command A",
        description: "Latest Cohere model with agentic capabilities.",
        contextWindow: 256000,
        outputTokens: 8192,
        tier: "flagship",
        speed: "powerful",
      },
    ],
  },

  // ── Perplexity ────────────────────────────────────────────────────────────
  {
    id: "perplexity",
    displayName: "Perplexity AI",
    shortName: "Perplexity",
    logoColor: "#20808D",
    models: [
      {
        id: "sonar-pro",
        displayName: "Sonar Pro",
        description: "Web-grounded reasoning model. Best for research with live citations.",
        contextWindow: 200000,
        outputTokens: 8192,
        tier: "flagship",
        speed: "balanced",
      },
      {
        id: "sonar",
        displayName: "Sonar",
        description: "Fast web-grounded model. Good for quick fact-checking.",
        contextWindow: 128000,
        outputTokens: 8192,
        tier: "balanced",
        speed: "fast",
      },
      {
        id: "sonar-reasoning-pro",
        displayName: "Sonar Reasoning Pro",
        description: "Deep reasoning with web grounding. Best for complex research questions.",
        contextWindow: 200000,
        outputTokens: 8192,
        tier: "flagship",
        speed: "powerful",
      },
    ],
  },

  // ── Amazon ────────────────────────────────────────────────────────────────
  {
    id: "amazon",
    displayName: "Amazon Web Services",
    shortName: "Amazon",
    logoColor: "#FF9900",
    models: [
      {
        id: "amazon.nova-pro-v1:0",
        displayName: "Nova Pro",
        description: "Amazon's flagship multimodal model. Best accuracy in the Nova family.",
        contextWindow: 300000,
        outputTokens: 5120,
        tier: "flagship",
        speed: "powerful",
      },
      {
        id: "amazon.nova-lite-v1:0",
        displayName: "Nova Lite",
        description: "Fast and cost-effective multimodal model.",
        contextWindow: 300000,
        outputTokens: 5120,
        tier: "lite",
        speed: "fast",
      },
      {
        id: "amazon.nova-micro-v1:0",
        displayName: "Nova Micro",
        description: "Text-only, lowest latency and cost in the Nova family.",
        contextWindow: 128000,
        outputTokens: 5120,
        tier: "lite",
        speed: "fast",
      },
    ],
  },

  // ── Microsoft ─────────────────────────────────────────────────────────────
  {
    id: "microsoft",
    displayName: "Microsoft",
    shortName: "Microsoft",
    logoColor: "#00A4EF",
    models: [
      {
        id: "phi-4",
        displayName: "Phi-4",
        description: "Small but powerful reasoning model. Excellent for structured tasks.",
        contextWindow: 16384,
        outputTokens: 4096,
        tier: "balanced",
        speed: "fast",
      },
      {
        id: "phi-4-mini",
        displayName: "Phi-4 Mini",
        description: "Ultra-compact reasoning model. Best for edge and low-latency scenarios.",
        contextWindow: 128000,
        outputTokens: 4096,
        tier: "lite",
        speed: "fast",
      },
      {
        id: "phi-4-multimodal",
        displayName: "Phi-4 Multimodal",
        description: "Phi-4 with vision and audio capabilities.",
        contextWindow: 128000,
        outputTokens: 4096,
        tier: "balanced",
        speed: "fast",
      },
    ],
  },

  // ── Alibaba (Qwen) ───────────────────────────────────────────────────────
  {
    id: "alibaba",
    displayName: "Alibaba Cloud (Qwen)",
    shortName: "Qwen",
    logoColor: "#FF6A00",
    models: [
      {
        id: "qwen-max",
        displayName: "Qwen Max",
        description: "Alibaba's flagship model. Strong multilingual and reasoning capabilities.",
        contextWindow: 128000,
        outputTokens: 8192,
        tier: "flagship",
        speed: "powerful",
      },
      {
        id: "qwen-plus",
        displayName: "Qwen Plus",
        description: "Balanced Qwen model. Good cost-performance for general tasks.",
        contextWindow: 128000,
        outputTokens: 8192,
        tier: "balanced",
        speed: "balanced",
      },
      {
        id: "qwen-turbo",
        displayName: "Qwen Turbo",
        description: "Fast Qwen variant. Optimized for high-throughput batch processing.",
        contextWindow: 128000,
        outputTokens: 8192,
        tier: "lite",
        speed: "fast",
      },
      {
        id: "qwen-coder-plus",
        displayName: "Qwen Coder Plus",
        description: "Specialized for code generation. Strong at structured output.",
        contextWindow: 128000,
        outputTokens: 8192,
        tier: "balanced",
        speed: "balanced",
      },
    ],
  },

  // ── AI21 Labs ─────────────────────────────────────────────────────────────
  {
    id: "ai21",
    displayName: "AI21 Labs",
    shortName: "AI21",
    logoColor: "#6C47FF",
    models: [
      {
        id: "jamba-1.5-large",
        displayName: "Jamba 1.5 Large",
        description: "SSM-Transformer hybrid. 256K context with efficient long-document processing.",
        contextWindow: 256000,
        outputTokens: 4096,
        tier: "flagship",
        speed: "balanced",
      },
      {
        id: "jamba-1.5-mini",
        displayName: "Jamba 1.5 Mini",
        description: "Compact Jamba model. Fast inference for structured tasks.",
        contextWindow: 256000,
        outputTokens: 4096,
        tier: "balanced",
        speed: "fast",
      },
    ],
  },
];

